region       = "eu-central-1"
instancetype = "t2.xlarge"
expire_on    = "2021-09-18"
purpose      = "training"
keyName      = "timolackmann"
keyPath      = "/Users/timo.lackmann/Downloads/timolackmann.pem"
ownerName    = "timo.lackmann"
initials     = "tl"